Create test configuration for "/vouchers/voucherstatuscheck/{voucherserialnumber}" endpoint - GET method
GovStackWorkingGroup/bb-payments pull request #10
Opened 2023-01-13 17:46 UTC by mgrochalskisoldevelo

Created mocks and cucumber tests

## Description
Create test configuration for /vouchers/voucherstatuscheck/{voucherserialnumber} endpoint (GET method) from .  This should include all the steps that are pointed out in the parent ticket.

TICKET: https://govstack-global.atlassian.net/browse/TECH-148

2023-01-17 09:35 UTC, KarolinaKopacz requested changes

2023-01-17 09:35 UTC, KarolinaKopacz commented on examples/mock/mockoon-paymentsbbvoucher.json
> +      "documentation": "Check the status of the Voucher. The API will respond with Not Pre-Activated Pre-Activated Activated Suspended Blocked Purged Not Existing",
```suggestion
      "documentation": "Check the status of the Voucher. The API will respond with Not Pre-Activated, Pre-Activated, Activated, Suspended, Blocked, Purged or Not Existing",
```

2023-01-17 09:35 UTC, KarolinaKopacz commented on test/features/support/voucher_status.js
> +// Scenario: The user is not able to check the status of the voucher because of the invalid voucher number
```suggestion
// Scenario: The user is not able to check the status of the voucher, because of the invalid voucher number
```

2023-01-17 09:35 UTC, KarolinaKopacz commented on test/features/support/voucher_status.js
> +  'The result of an operation returns an error because of the invalid voucher number',
```suggestion
  'The result of an operation returns an error, because of the invalid voucher number',
```

2023-01-17 09:35 UTC, KarolinaKopacz commented on test/features/support/voucher_status.js
> +// Scenario: The user is not able to check the status of the voucher because of the already used voucher number
```suggestion
// Scenario: The user is not able to check the status of the voucher, because of the already used voucher number
```

2023-01-17 09:35 UTC, KarolinaKopacz commented on test/features/support/voucher_status.js
> +  'The result of an operation returns an error because of the already used voucher number',
```suggestion
  'The result of an operation returns an error, because of the already used voucher number',
```

2023-01-17 09:35 UTC, KarolinaKopacz commented on test/features/support/voucher_status.js
> +// Scenario: The user is not able to check the status of the voucher that has expired
```suggestion
// Scenario: The user is not able to check the status of an expired voucher
```

2023-01-17 09:35 UTC, KarolinaKopacz commented on test/features/support/voucher_status.js
> +  'The result of an operation returns an error because of the expired voucher',
```suggestion
  'The result of an operation returns an error, because of the expired voucher',
```

2023-01-17 09:35 UTC, KarolinaKopacz commented on test/features/support/voucher_status.js
> +// Scenario: The user is not able to check the status of the voucher because of the empty payload
```suggestion
// Scenario: The user is not able to check the status of the voucher, because of the empty payload
```

2023-01-17 09:35 UTC, KarolinaKopacz commented on test/features/support/voucher_status.js
> +// Scenario: The user is not able to check the status of the voucher because of the Gov Stack Building Block does not exist
```suggestion
// Scenario: The user is not able to check the status of the voucher, because the Gov Stack Building Block does not exist
```

2023-01-17 09:35 UTC, KarolinaKopacz commented on test/features/support/voucher_status.js
> +  'The result of an operation returns an error because of the not existing Gov Stack Building Block',
```suggestion
  'The result of an operation returns an error, because of the not existing Gov Stack Building Block',
```

2023-01-17 11:32 UTC, KarolinaKopacz requested changes

2023-01-17 11:32 UTC, KarolinaKopacz commented on test/features/support/voucher_status.js
> +  'The result of an operation returns an error, because of the not existing Gov Stack Building Block',
```suggestion
  'The result of an operation returns an error, because the Gov Stack Building Block does not exist',
```

2023-01-17 12:19 UTC, dborowiecki approved these changes
LGTM, please apply Karolina's suggestion for name in mockoon definition.

2023-01-18 18:47 UTC, oscarcorreia43 approved these changes

2023-01-20 12:04 UTC, merged

2023-01-20 12:05 UTC, dborowiecki commented
Thanks for resolving conflicts, merged.