TECH-150: Add OpenAPI spec for Voucher APIs
GovStackWorkingGroup/bb-payments pull request #4
Opened 2023-01-03 14:02 UTC by KarolinaKopacz

Add OpenAPI spec for Voucher APIs 

## Description
Add OpenAPI spec for Voucher APIs. Verified linked APIs and add them to repository

2023-01-03 17:38 UTC, conradsp requested changes
I think the API definitions look good. Just requesting a couple of minor changes to the information at the top of this spec file.

2023-01-04 12:07 UTC, KarolinaKopacz commented on test/Payment_BB_Voucher_api_test
> +      'contact': { 'email': 'oscar.correia@maarifaeducation.com' },
Okay!
vijay.mauree@itu.int I found this email address on slack - is it correct?

2023-01-04 19:45 UTC, conradsp commented on test/Payment_BB_Voucher_api_test
> +      'contact': { 'email': 'oscar.correia@maarifaeducation.com' },
Yes, that email will work!

2023-01-05 10:50 UTC, KarolinaKopacz commented
@conradsp  I realized that in the `api` folder, files `swagger.json` and `swagger.yaml` are empty.
If you do not mind I will add API specs to these files. In that case, do you think we should also keep API specs in the `test` folder as I did?

2023-01-05 10:53 UTC, rachellawson commented
I seem to remember there being a complex history around the apis in payments. Not sure who would be able to give detail. Jaume?

2023-01-05 11:07 UTC, KarolinaKopacz commented
@rachellawson 
Thank you for your comment.
Before starting working on cucumber test for Payments BB - Voucher APIs we received form Vijay Mauree the link to the swagger with correct API specs here: https://app.swaggerhub.com/apis/AKibuuka/voucher/1.0.3#/VoucherPreactivation/VoucherPreactivationPOST :)

2023-01-14 13:52 UTC, dborowiecki approved these changes

2023-01-16 11:43 UTC, KarolinaKopacz commented
Hi @conradsp and @oscarcorreia43 ,
Can we merge the PR?

2023-01-20 09:58 UTC, merged